theme: jekyll-theme-cayman
title: Chinese NLP
description: Datasets, SOTA results of every fields of Chinese NLP
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-135652957-1